development:
  adapter: mysql2
  database: multiser_tienda_dev
  username: multiser_tienda
  password: password
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  database: multiser_tienda_test
  username: multiser_tienda
  password: password
  pool: 5
  timeout: 5000
production:
  adapter: mysql2
  database: multiser_tienda
  username: multiser_tienda
  password: password
